# Generated by Django 2.2.3 on 2020-02-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=250)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('edu_qualification', models.CharField(max_length=500)),
                ('skills', models.CharField(max_length=100)),
            ],
        ),
    ]
